[project]
name = "hunter-nexus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "juliogo666-art", email = "julio.go666@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
hunter-nexus = "hunter_nexus:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
